version: '3'

services:
  duckbot-app:
    build:
      context: ""
      dockerfile: Dockerfile
      target: duckbot_dev
    volumes:
      - "./:/code"
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      REDIS_URL: redis://rq-redis:6379
    entrypoint: [
        "python", "-m", "flask", "run", "--eager-loading"
    ]
    depends_on:
      - duckbot-worker
      - rq-redis

  duckbot-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: duckbot_worker
    volumes:
      - "./:/code"
    environment:
      REDIS_URL: redis://rq-redis:6379
    env_file: .env
    depends_on:
      - rq-redis

  rq-redis:
    image: "redis:alpine"
